# Tensor
- Tensor(텐서): 배열, 행렬과 유사한 자료구조(특히 NumPy의 ndarray와 유사)
    - 자동 미분(automatic differentiation)에 최적화

In [1]:
import torch
import numpy as np

## 1. Initialize Tensor

In [2]:
# directly generate a tensor from data
data = [
    [1, 2],
    [3, 4]
]
x_data = torch.tensor(data)
print(x_data, x_data.dtype)

tensor([[1, 2],
        [3, 4]]) torch.int64


In [3]:
# generate a tensor from numpy's array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np, x_np.dtype)

tensor([[1, 2],
        [3, 4]]) torch.int64


In [5]:
# generate a tensor from other tensor
x_ones = torch.ones_like(x_data)
print(x_ones, x_ones.dtype)

x_rand = torch.rand_like(x_np, dtype=torch.float64)
print(x_rand, x_rand.dtype)

tensor([[1, 1],
        [1, 1]]) torch.int64
tensor([[0.7954, 0.9679],
        [0.3293, 0.7113]], dtype=torch.float64) torch.float64


In [9]:
# use random or constant values
shape = (2, 3,) # 2 x 3 shape
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor, '\n')
print(ones_tensor, '\n')
print(zeros_tensor)

tensor([[0.0197, 0.0914, 0.2466],
        [0.3351, 0.8240, 0.4925]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 2. Tensor Attributes

In [11]:
tensor_rand = torch.rand(3, 4)

print(tensor_rand)
print(f'Shape of tensor: {tensor_rand.shape}')
print(f'Datatype of tensor: {tensor_rand.dtype}')
print(f'Device tensor is stored on: {tensor_rand.device}')

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu') # if GPU exists, move tensor in CPU to GPU
print(device)

tensor_rand = tensor_rand.to(device)
print(f'Device tensor is stored on: {tensor_rand.device}')

tensor([[0.4745, 0.6935, 0.7354, 0.8944],
        [0.2210, 0.8991, 0.1913, 0.0466],
        [0.4702, 0.1596, 0.4828, 0.2836]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
cuda:0
Device tensor is stored on: cuda:0


## 3. Tensor Operations

In [15]:
# Indexing & Slicing
tensor_ones = torch.ones(4, 4)

print(tensor_ones)
print(f'First row: {tensor_ones[0]}')
print(f'First column: {tensor_ones[:, 0]}')
print(f'Last column: {tensor_ones[:, -1]}')

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])


In [18]:
# Concatenate some tensors
t1 = torch.cat([tensor_ones, tensor_ones, tensor_ones], dim=0) # 행에 붙임
print(t1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [19]:
# Concatenate some tensors
t2 = torch.cat([tensor_ones, tensor_ones, tensor_ones], dim=1) # 열에 붙임
print(t2)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [21]:
# Arithmetic operations
# Matrix multiplication = matmul() = @
# Transpose of A: A.T

y1 = tensor_ones @ tensor_ones.T
print(y1)

print()

y2 = tensor_ones.matmul(tensor_ones.T)
print(y2)

print()

y3 = torch.rand_like(y1)
torch.matmul(tensor_ones, tensor_ones.T, out=y3)
print(y3)
print()

# element-wise product - Hadamard product
z1 = tensor_ones * tensor_ones
print(z1)
print()

z2 = tensor_ones.mul(tensor_ones)
print(z2)
print()

z3 = torch.rand_like(tensor_ones)
torch.mul(tensor_ones, tensor_ones, out=z3)
print(z3)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [23]:
# single-element tensor
agg = tensor_ones.sum()
agg_item = agg.item() # tensor transform to python value
print(agg_item, type(agg_item))

16.0 <class 'float'>


In [24]:
# in-place operation ~ _
print(tensor_ones)

tensor_ones.add_(5)
print(tensor_ones) # not encourage to use

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


## 4. NumPy Bridge

In [27]:
t = torch.ones(5)
print(f't: {t}, {t.dtype}')

t: tensor([1., 1., 1., 1., 1.]), torch.float32


In [28]:
n = t.numpy()
print(f'n: {n}, {n.dtype}')

n: [1. 1. 1. 1. 1.], float32


In [29]:
t.add_(1)
print(t)

tensor([2., 2., 2., 2., 2.])
